### ISSUE TITLE
Problem with subscription to SelfState in "Explore" 

### ISSUE THREAD

**Issue by johnathanDOS** [MistyCommunity/MistyI#6]
There seems to be a bug in the Explore script where the subscription to SelfState does not access the appropriate message, which prevents the rest of the script from executing correctly.

**Comment by sollazzo08** [comment]
This is a copy of my post from the Misty Community Forum.

I was attempted to run Misty’s Explore Skill under the SampleCode repo. I was able to connect to Misty and run the skill in the browser. Misty then proceeds to set her pitch but never proceeds to move. I am thinking it is because I don’t have a map for Misty. Here is the error I get with the console. I also have the log file. 

How can I send the log file?

[
<img width="637" alt="Screen Shot 2020-02-14 at 3 34 18 PM" src="https://user-images.githubusercontent.com/37941330/74578034-57feea00-4f60-11ea-94a5-2dbf0d98314f.png">
](url)

**Comment by johnathanDOS** [comment]
"Explore" code & details for this issue [copied to REST-API repository](https://github.com/MistyCommunity/JavaScript-SDK/issues/6). Closing issue in this repository as the corresponding project is no longer in this repo.
